name: sentence_coach
channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - scipy
  - pip
  - pip:
    - transformers
    - accelerate
    - pyttsx3
    - sounddevice
    - pillow
    - torchvision
    - fastapi
    - "uvicorn[standard]"
    - python-multipart
    - numpy
    - soundfile
    - faster-whisper
    - openai
    - kokoro-onnx
    - websockets
    - pytest
